### ISSUE TITLE
No region proposals detected

### ISSUE THREAD

**Issue by athmanal** [imatge-upc/retrieval-2016-deepvision#1]
Hi while running features.py I keep getting tis error:

  File "/home/Athma/Downloads/InstanceSearch/retrieval-2016-deepvision/test.py", line 76, in _get_rois_blob
    rois, levels = _project_im_rois(im_rois, im_scale_factors)
  File "/home/Athma/Downloads/InstanceSearch/retrieval-2016-deepvision/test.py", line 91, in _project_im_rois
    im_rois = im_rois.astype(np.float, copy=False)
AttributeError: 'NoneType' object has no attribute 'astype'

My caffe installation of faster rcnn seems to be working just fine. and network gets loaded in caffe.
this is where the issue comes:

I0509 13:05:38.588491 22199 net.cpp:270] This network produces output bbox_pred
I0509 13:05:38.588496 22199 net.cpp:270] This network produces output cls_prob
I0509 13:05:38.588518 22199 net.cpp:283] Network initialization done.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 548317115
I0509 13:05:39.171497 22199 net.cpp:816] Ignoring source layer data
I0509 13:05:39.247697 22199 net.cpp:816] Ignoring source layer loss_cls
I0509 13:05:39.247720 22199 net.cpp:816] Ignoring source layer loss_bbox
I0509 13:05:39.249155 22199 net.cpp:816] Ignoring source layer silence_rpn_cls_score
I0509 13:05:39.249172 22199 net.cpp:816] Ignoring source layer silence_rpn_bbox_pred
Extracting database features...
--Traceback ERROR---

**Comment by athmanal** [comment]
Hi,I detected the issue.We need to set cfg.TEST.has_RPN='TRUE'

**Comment by hackershi** [comment]
Actually, it's cfg.TEST.HAS_RPN ='TRUE'
