### ISSUE TITLE
wrong dataset name

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [imatge-upc/retrieval-2016-deepvision#6]
```
        # PCA MODEL - use paris for oxford data and vice versa
        if self.dataset is 'paris':

            self.pca = pickle.load(open(params['pca_model'] + '_oxford.pkl', 'rb'))

        elif self.dataset is 'oxford':

            self.pca = pickle.load(open(params['pca_model'] + '_paris.pkl', 'rb'))
```

the names of dataset are exchanged.

**Comment by amaiasalvador** [comment]
They are exchanged on purpose. PCA models are trained on Oxford to be applied on Paris and viceversa.

**Comment by zimenglan-sysu-512** [comment]
@amaiasalvador  can you explain why? thanks.

**Comment by amaiasalvador** [comment]
We basically decided to do this to be consistent with other works in the literature in which PCA was also trained on Oxford and tested on Paris and viceversa. This is explained in the paper. You can find the references there.

**Comment by zimenglan-sysu-512** [comment]
@amaiasalvador thanks.

**Comment by hana9090** [comment]
Why did you make PCA? is it a kind of clustering ? which is the K-mean?
