### ISSUE TITLE
incompletelly downloading oxford and paris dataset?

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [imatge-upc/retrieval-2016-deepvision#7]
i run the script `get_oxford.sh` and `get_paris.sh` to download the dataset, but i found that only 1059 images for `oxford` and 2794 images for `paris`. while in your paper, there are 5063 images for `oxford` and 6412 for `paris`.
btw,  i run `ranker.py`, and found `ValueError: could not broadcast input array from shape (0,512) into shape (512)`, i guess that it causes by missing some images.

thanks.

**Comment by amaiasalvador** [comment]
The scripts `get_oxford.sh` and `get_paris.sh` simply download the datasets from their original source, and then extract the compressed files to get the jpg images organized to work with the code. I just tried to run them both and got all images without any problems, and was able to run the whole pipeline following the steps that are provided in the README. 

Make sure that the download process is not interrupted. Images are first downloaded in compressed files, which are later extracted to get the jpg images. If the download is interrupted, you still might be able to extract the compressed file but will get less images.

**Comment by zimenglan-sysu-512** [comment]
@amaiasalvador thanks a lot.
